apiVersion: v1
kind: Service
metadata:
  name: nblotti-pheidippides
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: nblotti_pheidippides
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

