package ch.nblotti.pheidippides.statemachine;

public enum EVENTS {
  EVENT_RECEIVED,
  WAIT_FOR_CLIENT,
  ZK_DB_EVENT_RECEIVED,
  ZK_STRATEGIES_EVENT_RECEIVED,
  ZK_CLIENT_CHANGE_EVENT_RECEIVED,
  EVENT_TREATED,
  SUCCESS,
  ERROR,
  QUIT;
}
